```yaml
name: student-infra

on:
  push:
    branches:
      - master
    paths:
      - '**/*.tf'

jobs:
  student-infra:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v7

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.6"

      - name: AWS Credentials Setup
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Check AWS Account
        run: |
          aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Verify EKS Cluster
        run: |
          aws eks describe-cluster \
            --name my-eks \
            --region ap-south-1 \
            --query 'cluster.status' \
            --output text
```
